apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bubble-animation-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: sha-dev
    server: https://kubernetes.default.svc 
  project: sha-dev-project 
  source: 
    path: bubble-animation/application-mainfest
    repoURL: https://github.com/waqar-ahmad1024/argocd-openshift
    targetRevision: main
  syncPolicy: 
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=false
